require 'huginn_agent'

#HuginnAgent.load 'huginn_brave_catalog_availabilty_counter_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_brave_catalog_availabilty_counter_agent/brave_catalog_availabilty_counter_agent'
